include: package:very_good_analysis/analysis_options.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - test/output/**
    - example/**
  errors:
    invalid_annotation_target: ignore
