name: firestore_builder
description: "The easiest way to integrate Firestore into a Flutter application"
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^2.3.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.11.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0

flutter: null
