name: firestore_builder
description: "An easy way to use firestore"
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^2.3.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.11.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0

flutter: null
