name: example
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.7
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  firestore_builder:
    path: ..
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

firestore_builder:
  output: lib/firestore
  clear: False
  collections:
    - users:
        model_name: user
        fields:
          - name: String
          - current_job: String?
          - age: int
    - messages:
        model_name: message
        fields:
          - content: String
          - date: DateTime
