name: example
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firestore_builder:
    path: ..

flutter:
  uses-material-design: true

firestore_builder:
  output: test/output
  collections:
    - users:
        fields:
          - name: string
          - age: number
    - messages:
        fields:
          - content: string
          - date: timestamp
